### ISSUE TITLE
source code for examples/*.html

### ISSUE THREAD

**Issue by umlaeute** [ch-nry/pd-pmpd#12]
the file [examples/00_pm_pmpd_and_expressive_mvt_synthesis.html](https://raw.githubusercontent.com/ch-nry/pd-pmpd/v0.13.1/examples/00_pm_pmpd_and_expressive_mvt_synthesis.html) is obviously generated.

could you also provide the source code that enables us to re-generate that file?

or maybe just clarify (here) how you did create the html-file.
e.g. `manual/*.odt` is the source code (the file you modify), which you export as `manual/*.pdf` with LibreOffice's built-in PDF exporter; then you run [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX) on that PDF to generate the HTML.

i just want to make sure i understand the process.

**Comment by ch-nry** [comment]
yes, the source file is the .odt file in manual/
The .pdf is an export from open office.
I used an online pdf2html converter. I test many and keep the file with the best formatting. I don't remember the converter used.
I don't have pdf2htmlEX, but if it generate a nice file, then there is no problem to use it to replace the .html file

**Comment by umlaeute** [comment]
I was just checking the html source, which suggested that `pdf2htmlEX` was used to do the conversion
