### ISSUE TITLE
LICENSE.txt vs LICENSE boilerplate

### ISSUE THREAD

**Issue by umlaeute** [ch-nry/pd-pmpd#13]
just a minor issue, but:

the boilerplate in the .c files declares that pmpd is GPL-v3+, e.g. https://github.com/ch-nry/pd-pmpd/blob/ff21afe1f25e155637117e9135107aa456b10e8d/iAmbient2D.c#L4-L7

however, the `LICENSE.txt` file only covers the GPL-2: https://github.com/ch-nry/pd-pmpd/blob/ff21afe1f25e155637117e9135107aa456b10e8d/LICENSE.txt#L1-L2

this basically puts the .c-files under the GPL-3+, and the rest of the code (Pd-patches,...) under the GPL-v2.

while not a problem per se, i think it would be good to use a consistent license (and if this is not intended, ship the full text of *each* (used) license)

**Comment by ch-nry** [comment]
I just update the LICENCE.txt file to be GPL3+
thanks for the heads-up.
