### ISSUE TITLE
the architecture specifier for `aarch64` should be `arm64`

### ISSUE THREAD

**Issue by umlaeute** [ch-nry/pd-pmpd#19]
There is https://github.com/ch-nry/pd-pmpd/blob/aa22fa4b5e759620abf46a1dd09ca47ff412c867/CMakeLists.txt#L35-L36

however, `aarch64` is just another name for the `arm64` architecture, and Pd will indeed use **`arm64`** as the file-name extension (cf https://github.com/pure-data/pure-data/blob/88a4ff1df5613f83be6232695d80e02a343bbd57/src/s_inter.c#L1143-L1144).

so the proper stanza would be:
```cmake
 elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES ".*aarch64.*") 
   set(arch "arm64") 
```

it seems like i overlooked this in my last round of fixes.

**Comment by ben-wes** [comment]
> so the proper stanza would be:
> 
> ```cmake
>  elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES ".*aarch64.*") 
>    set(arch "amd64") 
> ```

... trying to avoid confusion (through `arm64` vs `amd64`) and to match the explanations (thank you!), i guess it should be:

```cmake
 elseif(${CMAKE_SYSTEM_PROCESSOR} MATCHES ".*aarch64.*") 
   set(arch "arm64") 
```

?

**Comment by umlaeute** [comment]
totally, i've updated my original report to fix this typo.

**Comment by ch-nry** [comment]
fixed with :  
https://github.com/ch-nry/pd-pmpd/commit/509e3c1a1faf51c9e17cd2fb23f80cbc046dec54
